# Generated by Django 3.2.9 on 2021-12-07 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('issue_date', models.DateField()),
                ('total_amount', models.FloatField()),
                ('rating', models.IntegerField()),
                ('maturity_date', models.DateField()),
                ('total_expected_interest_amount', models.FloatField()),
                ('invested_amount', models.FloatField(blank=True, null=True)),
                ('investment_date', models.DateField(blank=True, null=True)),
                ('expected_interest_amount', models.FloatField(blank=True, null=True)),
                ('is_closed', models.BooleanField(blank=True, null=True)),
                ('expected_irr', models.FloatField(blank=True, null=True)),
                ('realized_irr', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.DateField()),
                ('type', models.CharField(choices=[('Funding', 'Funding'), ('Repayment', 'Repayment')], max_length=100)),
                ('amount', models.FloatField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loanapp.loan')),
            ],
        ),
    ]
